version: '3.8'

services:
  postgres:
    image: 'postgres'
    container_name: 'prueba1_dev'
    environment:
       POSTGRES_DB: 'postgres'
       POSTGRES_USER: 'postgres'
       POSTGRES_PASSWORD: 'password'
       ALLOW_IP_RANGE: '0.0.0.0/0'
    ports:
      - '5432:5432'